SELECT
  d.dm_states_name AS damage_scale_dm_states_name,
  d.dm_scale_reference AS damage_scale_reference,
  e.description AS edp_description,
  e.units AS edp_units,
  i.definition AS im_table_definition,
  i.range AS im_table_range,
  i.units AS im_table_units,
  f.an_analysis_type,
  f.an_model_type,
  f.approach,
  f.asset,
  f.bespoke_model_ref,
  f.country_iso,
  f.damage_scale_name,
  f.data_countries,
  f.dm_scale_reference,
  f.dm_scale_type,
  f.dm_state_f_name,
  f.dm_states_name,
  f.edp_dmstate_thre,
  f.edp_name_all,
  f.em_analysis_type,
  f.fit_ref,
  f.ff_disc_ep,
  f.ff_disc_im,
  f.ff_math,
  f.ff_math_modelf,
  f.ff_relationship,
  f.hazard,
  f.id,
  f.im_data_source,
  f.im_range,
  f.im_method,
  f.im_name_f,
  f.im_sim_type,
  f.impe_reference,
  f.is_data_aggregated,
  f.is_data_disaggr,
  f.is_existing_val_study,
  f.is_fit_good,
  f.is_fix_nonsamp_err,
  f.is_validation,
  f.jd_analysis_type,
  f.lb_par_perc,
  f.lb_par_value,
  f.med_par_value,
  f.n_dm_states,
  f.n_events,
  f.n_assets,
  f.n_data_points_aggr,
  f.n_data_points_disaggr,
  f.nonsampling_err,
  f.par_names,
  f.reference,
  f.sample_f,
  f.scale_applicability,
  f.sub_asset,
  f.taxonomy,
  f.type_nonsampling_err,
  f.ub_par_perc,
  f.ub_par_value,
  f.val_data_source,
  f.val_study_reference,
  r.title AS reference_title,
  r.author_year AS reference_author_year
FROM vulnerabilities.ff_table AS f
  LEFT OUTER JOIN vulnerabilities.damage_scale AS d ON (d.damage_scale_name = f.damage_scale_name)
  LEFT OUTER JOIN vulnerabilities.im_table AS i ON (i.im_name_f = f.im_name_f)
  LEFT OUTER JOIN vulnerabilities.reference_table AS r ON (r.author_year = f.bespoke_model_ref)
  LEFT OUTER JOIN vulnerabilities.edp AS e ON (e.edp_name_f = f.edp_name_all)
WHERE f.id = %(pk)s
