SELECT
  i.definition AS im_table_definition,
  i.im_name_f,
  i.range AS im_table_range,
  i.units AS im_table_units,
  p.description AS lp_description,
  p.lp_name,
  p.units AS lp_units,
  v.an_analysis_type,
  v.an_model_type,
  v.approach,
  v.asset,
  v.bespoke_model_ref,
  v.country_iso,
  v.data_countries,
  v.em_analysis_type,
  v.fit_ref,
  v.hazard,
  v.id,
  v.im_data_source,
  v.im_method,
  v.im_sim_type,
  v.im_range,
  v.impe_reference,
  v.is_data_aggregated,
  v.is_data_disaggr,
  v.is_existing_val_study,
  v.is_fit_good,
  v.is_fix_nonsamp_err,
  v.is_validation,
  v.jd_analysis_type,
  v.lb_par_perc,
  v.lb_par_value,
  v.med_par_value,
  v.n_events,
  v.n_assets,
  v.n_data_points_aggr,
  v.n_data_points_disaggr,
  v.nonsampling_err,
  v.par_names,
  v.reference,
  v.sample_f,
  v.scale_applicability,
  v.sub_asset,
  v.taxonomy,
  v.type_nonsampling_err,
  v.ub_par_perc,
  v.ub_par_value,
  v.val_data_source,
  v.val_study_reference,
  v.vf_disc_ep,
  v.vf_disc_im,
  v.vf_math,
  v.vf_math_model,
  v.vf_relationship
FROM vulnerabilities.vf_table AS v
  LEFT OUTER JOIN vulnerabilities.loss_parameter AS p ON (p.lp_name = v.lp_name)
  LEFT OUTER JOIN vulnerabilities.im_table AS i ON (i.im_name_f = v.im_name_f)
WHERE v.id = %(pk)s
