# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-07 11:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import gfdrr_det.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gfdrr_det', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRepresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(help_text=b"Identifier for the dataset in the dataset type's database", max_length=255, unique=True)),
                ('dataset_type', models.CharField(max_length=255, validators=[gfdrr_det.validators.validate_dataset_type])),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text=b'Compound geometry of all the records in the dataset', srid=4326)),
                ('administrative_levels', models.ManyToManyField(related_name='dataset_representations', to='gfdrr_det.AdministrativeDivision')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='datasetrepresentation',
            unique_together=set([('dataset_id', 'dataset_type')]),
        ),
    ]
