# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-07 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfdrr_det', '0002_auto_20180307_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetrepresentation',
            old_name='administrative_levels',
            new_name='administrative_divisions',
        ),
    ]
