# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-07 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfdrr_det', '0003_auto_20180307_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrepresentation',
            name='name',
            field=models.CharField(default='dummy', help_text=b'Name of this dataset', max_length=255),
            preserve_default=False,
        ),
    ]
