# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gfdrr_det.validators
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0030_auto_20180228_0812'),
        ('gfdrr_det', '0004_datasetrepresentation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeveDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(choices=[(b'exposure', b'exposure'), (b'hazard', b'hazard')], max_length=20, validators=[gfdrr_det.validators.validate_dataset_type])),
                ('details', jsonfield.fields.JSONField(blank=True, null=True)),
                ('layer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
            ],
        ),
    ]
